# Generated by Django 5.2.9 on 2025-12-19 17:17

import django.core.validators
import core.utils.upload_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='distance_traveled_km',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='routes_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spot_created',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_thum_path',
            field=models.ImageField(blank=True, help_text='Formatos: JPG, PNG, WEBP', null=True, upload_to=core.utils.upload_image.user_thumbnail_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
