# Generated by Django 5.2.10 on 2026-04-01 15:56

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots_routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routephoto',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='spots_routes.route'),
        ),
        migrations.AddField(
            model_name='routephoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spot',
            name='reviewed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='spots_routes.spot'),
        ),
        migrations.AddField(
            model_name='spotcaption',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='spots_routes.spot'),
        ),
        migrations.AddField(
            model_name='spotcaption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spot',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spots_routes.spotstatusreview'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_with_mode', to='spots_routes.travelmode'),
        ),
        migrations.AddField(
            model_name='userfavoriteroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='spots_routes.route'),
        ),
        migrations.AddField(
            model_name='userfavoriteroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfavoritespot',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='spots_routes.spot'),
        ),
        migrations.AddField(
            model_name='userfavoritespot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='routephoto',
            index=models.Index(fields=['route', '-created_at'], name='spots_route_route_i_b1ebc4_idx'),
        ),
        migrations.AddIndex(
            model_name='routephoto',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_e44afc_idx'),
        ),
        migrations.AddIndex(
            model_name='spotcaption',
            index=models.Index(fields=['spot', '-created_at'], name='spots_route_spot_id_817ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='spotcaption',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_205792_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['status', '-created_at'], name='spots_route_status__389486_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_5dbe20_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['is_active', 'status'], name='spots_route_is_acti_6cbfb4_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='spots_route_locatio_8ad100_gist'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['spot', '-created_at'], name='spots_route_spot_id_c5b1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_285250_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['difficulty'], name='spots_route_difficu_9474a3_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['travel_mode'], name='spots_route_travel__dde0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoriteroute',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_60853a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoriteroute',
            unique_together={('user', 'route')},
        ),
    ]
