# Generated by Django 5.2.7 on 2025-11-15 00:50

import django.db.models.deletion
import spots_routes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0002_seed_spot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='reviewed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spot',
            name='status',
            field=models.ForeignKey(default=spots_routes.models.get_default_pending, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spots_routes.spotstatusreview'),
        ),
    ]
