# Generated by Django 5.2.13 on 2026-04-17 20:34

import core.utils.upload_image
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0003_seed_spot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_thumbnail_path',
            field=models.ImageField(help_text='Formatos: JPG, PNG, WEBP', upload_to=core.utils.upload_image.upload_spot_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
