# Generated by Django 5.2.8 on 2025-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0003_alter_spot_reviewed_user_alter_spot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
