# Generated by Django 5.2.8 on 2025-12-11 15:54

import django.contrib.gis.db.models.fields
import django.core.validators
import core.utils.upload_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0004_alter_spot_reviewed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotcaption',
            name='caption',
        ),
        migrations.AddField(
            model_name='routephoto',
            name='coords',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='spotcaption',
            name='img_path',
            field=models.ImageField(default='123.jpg', help_text='Formatos: JPG, PNG, WEBP', upload_to=core.utils.upload_image.spot_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routephoto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routephoto',
            name='img_path',
            field=models.ImageField(help_text='Formatos: JPG, PNG, WEBP', upload_to=core.utils.upload_image.route_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_thumbnail_path',
            field=models.ImageField(help_text='Formatos: JPG, PNG, WEBP', upload_to=core.utils.upload_image.spot_thumbnail_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
