# Generated by Django 5.2.13 on 2026-04-17 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0005_alter_spot_spot_thumbnail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='storage_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
