# Generated by Django 5.2.9 on 2025-12-16 23:12

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0006_seed_dificulties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routephoto',
            name='coords',
        ),
        migrations.AddField(
            model_name='routephoto',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='route',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoriteroute',
            unique_together={('user', 'route')},
        ),
        migrations.AddIndex(
            model_name='userfavoriteroute',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_60853a_idx'),
        ),
    ]
