# Generated by Django 5.2.9 on 2025-12-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0007_remove_routephoto_coords_routephoto_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoriteroute',
            name='spot',
        ),
    ]
