# Generated by Django 5.2.9 on 2025-12-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0008_remove_userfavoriteroute_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
