# Generated by Django 5.2.10 on 2026-01-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0009_alter_route_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='routephoto',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='spotcaption',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userfavoritespot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='spot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spotcaption',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotcaption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userfavoritespot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2026-01-23 17:44:38.397736+00'),
            preserve_default=False,
        ),
    ]
