# Generated by Django 5.2.10 on 2026-01-25 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0010_alter_route_options_alter_routephoto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.AlterModelOptions(
            name='routephoto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spotcaption',
            options={},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['spot', '-created_at'], name='spots_route_spot_id_c5b1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_285250_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['difficulty'], name='spots_route_difficu_9474a3_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['travel_mode'], name='spots_route_travel__dde0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='routephoto',
            index=models.Index(fields=['route', '-created_at'], name='spots_route_route_i_b1ebc4_idx'),
        ),
        migrations.AddIndex(
            model_name='routephoto',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_e44afc_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['status', '-created_at'], name='spots_route_status__389486_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_5dbe20_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['is_active', 'status'], name='spots_route_is_acti_6cbfb4_idx'),
        ),
        migrations.AddIndex(
            model_name='spotcaption',
            index=models.Index(fields=['spot', '-created_at'], name='spots_route_spot_id_817ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='spotcaption',
            index=models.Index(fields=['user', '-created_at'], name='spots_route_user_id_205792_idx'),
        ),
    ]
