# Generated by Django 5.2.10 on 2026-01-26 18:29

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots_routes', '0011_alter_route_options_alter_routephoto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spot',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='spots_route_locatio_8ad100_gist'),
        ),
    ]
